### ISSUE TITLE
Type declarations: use string type instead of String constructor class as type

### ISSUE THREAD

**Issue by CasperEngl** [mogelbrod/widont#13]
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

Today I used [patch-package](https://github.com/ds300/patch-package) to patch `widont@0.3.3` for the project I'm working on.

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/widont/index.d.ts b/node_modules/widont/index.d.ts
index 0c6d32b..33bb156 100644
--- a/node_modules/widont/index.d.ts
+++ b/node_modules/widont/index.d.ts
@@ -3,14 +3,14 @@ export as namespace widont;
 export = widont;
 
 declare function widont(
-  str: String,
+  str: string,
   replacements?: widont.Replacements,
-) : String;
+) : string;
 
 declare namespace widont {
   interface ReplacementsObj {
-    space: String;
-    hyphen: String;
+    space: string;
+    hyphen: string;
   }
 
   type Replacements = ReplacementsObj | 'unicode' | 'html' | 'ascii';
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

**Comment by mogelbrod** [comment]
Hi Casper, thanks for reporting this!
I've released a new version (v0.3.4) that fixes this - feel free to reopen this issue if there are any other typescript issues 👍
